version: '3.8'

services:
    web:
        build: .
        command: gunicorn --bind 0.0.0.0:5000 {{cookiecutter.app_name}}.manage:cli
        ports:
            - 5000:5000
        env_file:
            - app/.env
        depends_on:
            - db
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
            POSTGRES_DB: test
        env_file:
            - app/.env
volumes:
    postgres_data
