version: '3.8'

services:
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
            POSTGRES_DB: test
        env_file:
            - {{cookiecutter.app_name}}/.env
        ports:
            - 5432:5432
        restart: always
    web:
        build: .
        environment:
            DATABASE_URI: postgresql+psycopg2://test:test@db/test
        ports:
            - 5000:5000
        env_file:
            - {{cookiecutter.app_name}}/.env
        depends_on:
            - db
volumes:
    postgres_data:
